// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-vRA-Ftj7xyJlFo-kY3vjkQ1Bn1O40Qs',
    appId: '1:541505886200:web:3a37e3274d16973594a80d',
    messagingSenderId: '541505886200',
    projectId: 'kfonlnp',
    authDomain: 'kfonlnp.firebaseapp.com',
    storageBucket: 'kfonlnp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6OBKlI7uUOP3uVngqISW7RIGF2H9CPhQ',
    appId: '1:541505886200:android:464240f2e8c06d2794a80d',
    messagingSenderId: '541505886200',
    projectId: 'kfonlnp',
    storageBucket: 'kfonlnp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcAtXssBF3cgk4Q7Js-ykiQuJA9txSRG8',
    appId: '1:541505886200:ios:0b9417c77b2334a794a80d',
    messagingSenderId: '541505886200',
    projectId: 'kfonlnp',
    storageBucket: 'kfonlnp.appspot.com',
    iosBundleId: 'co.in.kfon.lnp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcAtXssBF3cgk4Q7Js-ykiQuJA9txSRG8',
    appId: '1:541505886200:ios:ad8f7781c3d5b9de94a80d',
    messagingSenderId: '541505886200',
    projectId: 'kfonlnp',
    storageBucket: 'kfonlnp.appspot.com',
    iosBundleId: 'com.change.package.mvvmbasic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-vRA-Ftj7xyJlFo-kY3vjkQ1Bn1O40Qs',
    appId: '1:541505886200:web:647af1ad444b733a94a80d',
    messagingSenderId: '541505886200',
    projectId: 'kfonlnp',
    authDomain: 'kfonlnp.firebaseapp.com',
    storageBucket: 'kfonlnp.appspot.com',
  );
}

